# Generated by Django 5.2.8 on 2025-11-17 07:59

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='last_embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='search_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PromptEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='prompts.prompt')),
            ],
            options={
                'indexes': [models.Index(fields=['prompt_id'], name='prompts_pro_prompt__a38f3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestOutputEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_embedding', pgvector.django.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='prompts.testrun')),
            ],
            options={
                'indexes': [models.Index(fields=['test_run_id'], name='prompts_tes_test_ru_cefb8d_idx')],
            },
        ),
    ]
