# Generated by Django 4.2.7 on 2025-11-19 06:57

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptembedding',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='testoutputembedding',
            name='test_run',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='last_embedded_at',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='search_enabled',
        ),
        migrations.AddField(
            model_name='prompt',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='prompt_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='version_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='testrun_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.DeleteModel(
            name='PromptEmbedding',
        ),
        migrations.DeleteModel(
            name='TestOutputEmbedding',
        ),
    ]
