# Generated by Django 4.2.7 on 2025-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_githubintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptversion',
            name='variables',
            field=models.JSONField(default=dict),
        ),
    ]
