# Generated by Django 4.2.7 on 2025-11-20 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0008_promptversion_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TEST', 'Test Run'), ('BENCHMARK', 'Benchmark Run'), ('BATCH', 'Batch Run'), ('SYNC', 'GitHub Sync'), ('ERROR', 'Error')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='prompts_aud_timesta_ee7b2f_idx'), models.Index(fields=['user', '-timestamp'], name='prompts_aud_user_id_859ca7_idx'), models.Index(fields=['tenant', '-timestamp'], name='prompts_aud_tenant__39f649_idx'), models.Index(fields=['model_name', '-timestamp'], name='prompts_aud_model_n_4a14fd_idx')],
            },
        ),
    ]
