# Generated by Django 5.2.8 on 2025-11-22 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0009_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Can be accessed by frontend without authentication')),
                ('category', models.CharField(default='general', help_text='Settings category (general, features, limits, etc.)', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='prompts_sys_categor_627fe8_idx'), models.Index(fields=['is_public'], name='prompts_sys_is_publ_368e30_idx')],
            },
        ),
    ]
