# Generated by Django 5.2.8 on 2025-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0011_seed_default_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='input_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='testrun',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testrun',
            name='output_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='testrun',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
